### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by lx324310** [ucb-bar/zscale#2]
HI everyone! and thanks for your works!
Is there any README or turtorial for how to run zscale?

**Comment by yunsup** [comment]
I'm in the process of bringing up the Z-scale simulation infrastructure within the rocket-chip repository.  Please stay tuned.

**Comment by yunsup** [comment]
Checkout the most recent commit on rocket-chip, and run the following commands:

$ cd /path/to/rocket/chip
$ cd vsim
$ make CONFIG=ZscaleConfig MODEL=ZscaleTop TB=ZscaleTestHarness
$ make CONFIG=ZscaleConfig MODEL=ZscaleTop TB=ZscaleTestHarness -j16 run-asm-tests

This should run all the 32-bit RISC-V tests on the Z-scale core.
