### ISSUE TITLE
Make firmware on Z-scale

### ISSUE THREAD

**Issue by ghost** [ucb-bar/zscale#6]
Dear,
    I want to build firmware to run on my fpga board. I use the script in the sw folder. There is an error as following.

riscv64-unknown-elf-gcc -m32 -static -Wa,-march=RVIM -std=gnu99 -O2 -fno-common -fno-builtin-printf -c -I./common -I./led -I./mbist ./common/trap.c -o trap.o
./common/trap.c: Assembler messages:
./common/trap.c:7: Error: Instruction csrw requires absolute expression
./common/trap.c:7: Error: Instruction csrw requires absolute expression
make: **\* [trap.o] Error 1

How should I do to solve this error? Thank you!!!

**Comment by zhemao** [comment]
When did you last install your compiler toolchain? We may have made some backwards-incompatible changes in the meantime. If your toolchain installation is more than a month old, I recommend you update it and try again.

**Comment by ghost** [comment]
Thank you very much!!! I recompile toolchain. It's working now.
